import { Vector2 } from './types';
export declare function generateId(): string;
export declare function clamp(value: number, min: number, max: number): number;
export declare function lerp(a: number, b: number, t: number): number;
export declare function lerpVector2(a: Vector2, b: Vector2, t: number): Vector2;
export declare function distance(a: Vector2, b: Vector2): number;
export declare function normalize(v: Vector2): Vector2;
export declare function dot(a: Vector2, b: Vector2): number;
export declare function magnitude(v: Vector2): number;
export declare function scale(v: Vector2, s: number): Vector2;
export declare function addVectors(a: Vector2, b: Vector2): Vector2;
export declare function subtractVectors(a: Vector2, b: Vector2): Vector2;
export declare function angle(from: Vector2, to: Vector2): number;
export declare function circleCollision(pos1: Vector2, r1: number, pos2: Vector2, r2: number): boolean;
export declare function clampVectorToBounds(v: Vector2, width: number, height: number, padding?: number): Vector2;
export declare function randomRange(min: number, max: number): number;
export declare function randomInt(min: number, max: number): number;
export declare function formatTime(seconds: number): string;
export declare function formatNumber(num: number): string;
export declare function deepClone<T>(obj: T): T;
export declare function debounce<T extends (...args: any[]) => any>(fn: T, delay: number): (...args: Parameters<T>) => void;
export declare function throttle<T extends (...args: any[]) => any>(fn: T, limit: number): (...args: Parameters<T>) => void;
